name: Auto Terraform Destroy

on:
  # codziennie o 20:00 UTC
  schedule:
    - cron: "0 20 * * *"

  # gdy PR do main zostanie ZAMKNIÄ˜TY (i ewentualnie zmergowany)
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  terraform-destroy:
    if: |
      github.event_name == 'schedule' ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.merged == true &&
       contains(github.event.pull_request.title, '[CLEANUP]'))

    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: .
      GOOGLE_PROJECT: tbd-2025z-2137
      GOOGLE_REGION: europe-west1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to GCP (Workload Identity)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure gcloud defaults
        run: |
          gcloud config set project $GOOGLE_PROJECT
          gcloud config set compute/region $GOOGLE_REGION

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve -input=false
