version: 0.1
resource_usage:
  google_storage_bucket.my_bucket:
    storage_gb: 150
    monthly_class_a_operations: 40000
    monthly_class_b_operations: 20000
    monthly_data_retrieval_gb: 500
    monthly_egress_data_transfer_gb:
      same_continent: 550
      worldwide: 12500
      asia: 1500
      china: 50
      australia: 250

  google_artifact_registry_repository.my_artifact_registry:
    storage_gb: 150
    monthly_egress_data_transfer_gb:
      europe_north1: 100
      australia_southeast1: 200

  google_service_networking_connection.my_connection:
    monthly_egress_data_transfer_gb:
      same_region: 250
      us_or_canada: 100
      europe: 70
      asia: 50
      south_america: 100
      oceania: 50
      worldwide: 200
